<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\Mes.Library.ObjectMapping\Mes.Library.ObjectMapping.csproj" />
    <ProjectReference Include="..\..\libraries\Mes.Library.RabbitMQ\Mes.Library.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\shared\Mes.Shared.Contracts\Mes.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
