<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mes.Library.RabbitMQ\Mes.Library.RabbitMQ.csproj"/>
        <ProjectReference Include="..\Mes.Library.SignalR\Mes.Library.SignalR.csproj" />
    </ItemGroup>

</Project>
