<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mes.Shopfloor.Api.SharedKernel\Mes.Shopfloor.Api.SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ProductDefinition\Requests\HttpContracts\" />
      <Folder Include="ProductDefinition\Requests\ModuleContracts\" />
    </ItemGroup>

</Project>
