<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mes.Library.Serialization\Mes.Library.Serialization.csproj"/>
    </ItemGroup>

</Project>
