<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\libraries\Mes.Library.Domain\Mes.Library.Domain.csproj"/>
        <ProjectReference Include="..\..\libraries\Mes.Library.RabbitMQ\Mes.Library.RabbitMQ.csproj"/>
        <ProjectReference Include="..\..\libraries\Mes.Library.ShopfloorCommands\Mes.Library.ShopfloorCommands.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="DataCollection\"/>
        <Folder Include="ProductDefinitionManagement\"/>
        <Folder Include="ProductionScheduling\"/>
        <Folder Include="ResourceManagement\"/>
    </ItemGroup>

</Project>
