<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DandyStrategies" />
    <PackageReference Include="Marten.AspNetCore" />
    <PackageReference Include="NLog.Web.AspNetCore" />
    <PackageReference Include="DandyEndpoints" />
    <PackageReference Include="DandyMediator.Validation" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\..\libraries\Mes.Library.EntityFrameworkCore\Mes.Library.EntityFrameworkCore.csproj"/>
    <ProjectReference Include="..\..\libraries\Mes.Library.Marten\Mes.Library.Marten.csproj" />
    <ProjectReference Include="..\Mes.Shopfloor.Shared.SharedKernel\Mes.Shopfloor.Shared.SharedKernel.csproj" />
  </ItemGroup>

</Project>
