// <auto-generated />
using System;
using System.Collections.Generic;
using Mes.Shopfloor.Api.ProductionManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mes.Shopfloor.Api.ProductionManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProductionManagementDbContext))]
    [Migration("20260701073035_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.Reject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("RejectGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("reject_group_id");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("RejectGroupId");

                    b.ToTable("reject", "data_collection");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.RejectGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("reject_group", "data_collection");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsIdle")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProductive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("StateGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_group_id");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("StateGroupId");

                    b.ToTable("state", "data_collection");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.StateGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("state_group", "data_collection");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.Status", b =>
                {
                    b.Property<Guid>("ProductionUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("production_unit_id");

                    b.HasKey("ProductionUnitId");

                    b.ToTable("status", "data_collection");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.StatusState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("ProductionUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_unit_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductionUnitId");

                    b.HasIndex("StateId");

                    b.ToTable("status_state", "data_collection");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("material", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("part", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProductionProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_process_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductionProcessId");

                    b.ToTable("product", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("production_process", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductionProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_process_id");

                    b.Property<Guid>("ProductionUnitGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_unit_group_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Duration", "Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep.Duration#Duration", b1 =>
                        {
                            b1.Property<double>("DeviationSeconds")
                                .HasColumnType("double precision")
                                .HasColumnName("duration_deviation_seconds");

                            b1.Property<TimeSpan>("Value")
                                .HasColumnType("interval")
                                .HasColumnName("duration_value");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductionProcessId");

                    b.ToTable("production_step", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepEquipment", b =>
                {
                    b.Property<Guid>("ProductionStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_step_id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("ProductionStepId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("production_step_equipment", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepMaterial", b =>
                {
                    b.Property<Guid>("ProductionStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_step_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("ProductionStepId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("production_step_material", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepParameter", b =>
                {
                    b.Property<Guid>("ProductionStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_step_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value");

                    b.HasKey("ProductionStepId", "Key");

                    b.ToTable("production_step_parameter", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepPart", b =>
                {
                    b.Property<Guid>("ProductionStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_step_id");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.HasKey("ProductionStepId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("production_step_part", "product_definition");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("equipment", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ManufacturingPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("manufacturing_plant", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("ShopfloorId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopfloor_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ShopfloorId");

                    b.ToTable("production_line", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProductionLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_line_id");

                    b.Property<Guid?>("ShopfloorId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopfloor_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("ShopfloorId");

                    b.HasIndex("TypeId");

                    b.ToTable("production_unit", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("RejectGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("reject_group_id");

                    b.Property<Guid>("StateGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_group_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("production_unit_type", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitGroupQualification", b =>
                {
                    b.Property<Guid>("WorkerQualificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_qualification_id");

                    b.Property<int>("ProductionUnitGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("production_unit_group_id");

                    b.HasKey("WorkerQualificationId", "ProductionUnitGroupId");

                    b.HasIndex("ProductionUnitGroupId");

                    b.ToTable("production_unit_group_qualification", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProductionUnitType");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Shopfloor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("ManufacturingPlantId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_plant_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingPlantId");

                    b.ToTable("shopfloor", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("Number")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("worker", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("worker_group", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerGroupWorkerQualification", b =>
                {
                    b.Property<Guid>("WorkerQualificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_qualification_id");

                    b.Property<Guid>("WorkerGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_group_id");

                    b.Property<Guid?>("WorkerGroupId1")
                        .HasColumnType("uuid");

                    b.HasKey("WorkerQualificationId", "WorkerGroupId");

                    b.HasIndex("WorkerGroupId");

                    b.HasIndex("WorkerGroupId1");

                    b.ToTable("worker_group_qualification", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("worker_qualification", "resources");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("production_order", "scheduling");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionOrderProgress", b =>
                {
                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.Property<double>("ProducedQuantity")
                        .HasColumnType("double precision")
                        .HasColumnName("produced_quantity");

                    b.Property<Guid?>("ProductionProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_process_id");

                    b.Property<Guid?>("ProductionProcessStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_process_step_id");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<double>("TargetQuantity")
                        .HasColumnType("double precision")
                        .HasColumnName("target_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProductionOrderId");

                    b.ToTable("production_order_progress", "scheduling");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionUnitSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductionUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_unit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("production_unit_schedule", "scheduling");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionUnitTask", b =>
                {
                    b.Property<Guid>("ProductionScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_schedule_Id");

                    b.Property<DateTime>("CompletingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completing_at");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.Property<Guid>("ProductionUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_unit_id");

                    b.Property<DateTime>("StartingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starting_at");

                    b.HasKey("ProductionScheduleId");

                    b.HasIndex("ProductionOrderId")
                        .IsUnique();

                    b.ToTable("production_unit_task", "scheduling");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.Reject", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.RejectGroup", "RejectGroup")
                        .WithMany("Rejects")
                        .HasForeignKey("RejectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RejectGroup");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.State", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.StateGroup", "StateGroup")
                        .WithMany("States")
                        .HasForeignKey("StateGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateGroup");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.StatusState", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.Status", null)
                        .WithMany("States")
                        .HasForeignKey("ProductionUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.Product", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionProcess", "ProductionProcess")
                        .WithMany()
                        .HasForeignKey("ProductionProcessId");

                    b.Navigation("ProductionProcess");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionProcess", null)
                        .WithMany("Steps")
                        .HasForeignKey("ProductionProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepEquipment", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep", "ProductionStep")
                        .WithMany("Equipment")
                        .HasForeignKey("ProductionStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ProductionStep");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepMaterial", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep", "ProductionStep")
                        .WithMany("Material")
                        .HasForeignKey("ProductionStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductionStep");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepParameter", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ProductionStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStepPart", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep", "ProductionStep")
                        .WithMany("Parts")
                        .HasForeignKey("ProductionStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("ProductionStep");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionLine", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Shopfloor", null)
                        .WithMany("ProductionLines")
                        .HasForeignKey("ShopfloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnit", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitGroup", "Group")
                        .WithMany("ProductionUnits")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionLine", null)
                        .WithMany("ProductionUnits")
                        .HasForeignKey("ProductionLineId");

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Shopfloor", null)
                        .WithMany("ProductionUnits")
                        .HasForeignKey("ShopfloorId");

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitGroupQualification", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitGroup", "ProductionUnitGroup")
                        .WithMany("RequiredQualifications")
                        .HasForeignKey("ProductionUnitGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerQualification", "WorkerQualification")
                        .WithMany("ProductionUnitGroups")
                        .HasForeignKey("WorkerQualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionUnitGroup");

                    b.Navigation("WorkerQualification");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Shopfloor", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ManufacturingPlant", null)
                        .WithMany("Shopfloors")
                        .HasForeignKey("ManufacturingPlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Worker", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerGroupWorkerQualification", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerGroup", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("WorkerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerGroup", "WorkerGroup")
                        .WithMany()
                        .HasForeignKey("WorkerGroupId1");

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerQualification", "WorkerQualification")
                        .WithMany("WorkerGroups")
                        .HasForeignKey("WorkerQualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkerGroup");

                    b.Navigation("WorkerQualification");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionOrderProgress", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionOrder", null)
                        .WithOne("Progress")
                        .HasForeignKey("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionOrderProgress", "ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionUnitTask", b =>
                {
                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionOrder", "Order")
                        .WithOne()
                        .HasForeignKey("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionUnitTask", "ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionUnitSchedule", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProductionScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.RejectGroup", b =>
                {
                    b.Navigation("Rejects");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.StateGroup", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.DataCollection.Status", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.ProductDefinition.ProductionStep", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Material");

                    b.Navigation("Parameters");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ManufacturingPlant", b =>
                {
                    b.Navigation("Shopfloors");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionLine", b =>
                {
                    b.Navigation("ProductionUnits");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.ProductionUnitGroup", b =>
                {
                    b.Navigation("ProductionUnits");

                    b.Navigation("RequiredQualifications");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.Shopfloor", b =>
                {
                    b.Navigation("ProductionLines");

                    b.Navigation("ProductionUnits");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerGroup", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Resources.WorkerQualification", b =>
                {
                    b.Navigation("ProductionUnitGroups");

                    b.Navigation("WorkerGroups");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionOrder", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("Mes.Shopfloor.Api.ProductionManagement.Subdomains.Scheduling.ProductionUnitSchedule", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
