<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Domain\Abstractions\Durational\" />
      <Folder Include="Domain\Abstractions\Scheduled\" />
      <Folder Include="Domain\Abstractions\Timestamped\" />
      <Folder Include="Extensions\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Mes.Shopfloor.Api.SharedKernel\Mes.Shopfloor.Api.SharedKernel.csproj" />
    </ItemGroup>

</Project>